obj-y													+= platform_ipc.o
obj-$(subst m,y,$(CONFIG_INTEL_MID_POWER_BUTTON))		+= platform_msic_power_btn.o
obj-$(subst m,y,$(CONFIG_KEYBOARD_GPIO))				+= platform_gpio_keys.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_ATMEL_MXT224S))	+= platform_atmxt-224s.o
obj-$(subst m,y,$(CONFIG_BATTERY_INTEL_MDF))			+= platform_msic_battery.o
obj-$(subst m,y,$(CONFIG_BATTERY_MAX17042))				+= platform_max17042.o
obj-$(subst m,y,$(CONFIG_MSIC_GPADC))					+= platform_msic_adc.o
obj-$(subst m,y,$(CONFIG_WILINK_PLATFORM_DATA))			+= platform_wl12xx.o
obj-$(subst m,y,$(CONFIG_TI_ST))						+= platform_btwilink.o
obj-$(subst m,y,$(CONFIG_SND_MFLD_MACHINE))				+= platform_msic_audio.o
obj-$(subst m,y,$(CONFIG_HSI_ARASAN))					+= platform_hsi_modem.o
obj-$(subst m,y,$(CONFIG_A1026))						+= platform_a1026.o
obj-$(CONFIG_BOARD_MFLD_MOTO)							+= platform_mmi-sensors.o
obj-$(subst m,y,$(CONFIG_VIDEO_ATOMISP))				+= platform_camera.o
ifdef CONFIG_VIDEO_ATOMISP
obj-$(subst m,y,$(CONFIG_VIDEO_MT9E013))				+= platform_mt9e013.o
obj-$(subst m,y,$(CONFIG_VIDEO_MT9M114))				+= platform_mt9m114.o
obj-$(subst m,y,$(CONFIG_VIDEO_SH833SU))				+= platform_sh833su.o
obj-$(subst m,y,$(CONFIG_VIDEO_LC898211))				+= platform_sh833su.o
obj-$(subst m,y,$(CONFIG_VIDEO_OV7736))					+= platform_ov7736.o
obj-$(subst m,y,$(CONFIG_VIDEO_OV8830))					+= platform_ov8830.o
obj-$(subst m,y,$(CONFIG_VIDEO_LM3554))					+= platform_lm3554.o
endif
obj-$(subst m,y,$(CONFIG_LEDS_LM2755))					+= platform_lm2755.o
