obj-y													+= platform_ipc.o
obj-$(subst m,y,$(CONFIG_INTEL_MID_POWER_BUTTON))		+= platform_msic_power_btn.o
obj-$(subst m,y,$(CONFIG_KEYBOARD_GPIO))				+= platform_gpio_keys.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_ATMEL_MXT224S))	+= platform_atmxt-224s.o
obj-$(subst m,y,$(CONFIG_BATTERY_INTEL_MDF))			+= platform_msic_battery.o
obj-$(subst m,y,$(CONFIG_BATTERY_MAX17042))				+= platform_max17042.o
obj-$(subst m,y,$(CONFIG_MSIC_GPADC))					+= platform_msic_adc.o
